apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: cicd-demo
type: Opaque
stringData:
  POSTGRES_USER: cicd
  POSTGRES_PASSWORD: cicd
  POSTGRES_DB: cicddb
  DATABASE_URL: postgresql://cicd:cicd@postgres-service:5432/cicddb
